# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksm < Formula
  desc ""
  homepage "https://github.com/ck0ne01/kubernetes-secrets-manager"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ck0ne01/kubernetes-secrets-manager/releases/download/0.2.1/kubernetes-secrets-manager_0.2.1_darwin_arm64.tar.gz"
      sha256 "ec6f737cc47b86cc29c425c2275d41622d6c0875d33c2714762f95d2d40f1cc2"

      def install
        bin.install "ksm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ck0ne01/kubernetes-secrets-manager/releases/download/0.2.1/kubernetes-secrets-manager_0.2.1_darwin_amd64.tar.gz"
      sha256 "58be39c457d0a8c687ab6a9ba2144aab85f95b67f0cf983e04baa7186e598afc"

      def install
        bin.install "ksm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ck0ne01/kubernetes-secrets-manager/releases/download/0.2.1/kubernetes-secrets-manager_0.2.1_linux_arm64.tar.gz"
      sha256 "a46367eca0fd4dd6e229071ef1b285582bca81cdf42aa3bcadfb572a45e40d7e"

      def install
        bin.install "ksm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ck0ne01/kubernetes-secrets-manager/releases/download/0.2.1/kubernetes-secrets-manager_0.2.1_linux_amd64.tar.gz"
      sha256 "17fa02911ccf8cf4c8dc7800a681e1ec2d86404e5074baeb64a6f027b0146b59"

      def install
        bin.install "ksm"
      end
    end
  end
end
