# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksm < Formula
  desc ""
  homepage "https://github.com/ck0ne01/kubernetes-secrets-manager"
  version "0.1.0"

  on_macos do
    url "https://github.com/ck0ne01/kubernetes-secrets-manager/releases/download/0.1.0/kubernetes-secrets-manager_0.1.0_darwin_all.tar.gz"
    sha256 "df51df7f9637e253898abc13fb9b83b2b9f5207e6b288e6950ccf2a021b62bb2"

    def install
      bin.install "kubernetes-secrets-manager"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ck0ne01/kubernetes-secrets-manager/releases/download/0.1.0/kubernetes-secrets-manager_0.1.0_linux_amd64.tar.gz"
      sha256 "30a793ab2556c9254094a554b9fc0a23d888a55e12a5b9b6b395958cb277972d"

      def install
        bin.install "ksm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ck0ne01/kubernetes-secrets-manager/releases/download/0.1.0/kubernetes-secrets-manager_0.1.0_linux_arm64.tar.gz"
      sha256 "f7437a2fa3f4f9313fb458bc251b2540bfce2b059915e88ab1f6dbb890a234ef"

      def install
        bin.install "ksm"
      end
    end
  end
end
